### PR TITLE
Changing url pathing. Query interface is now the base url.

### PR DESCRIPTION
**Pull request by jarmoza**
Linked to issue https://github.com/metaneuro/concept_query/issues/37

### CODE REVIEW

**Comment by jarmoza** [comment]
@surchs Shall we include query string functionality with this PR as discussed in #37 ?

**Comment by surchs** [comment]
I'd say let's make two separate PRs for routing and query string, mostly because we'll want to make sure the tests are working and we keep track of the changes. On that note: can you run the functional tests and adapt them according to the url changes?

**Comment by surchs** [comment]
Hey @jarmoza: thanks for looking into the functional test on circleCI. Just wanted to clarify: for now it'd be enough to run functional tests locally and make sure the URL changes didn't break things (the test paths probably need updating). We can figure out how to get the functional tests to run on circleCI in a separate PR later.

**Comment by jarmoza** [comment]
"Reverted" changes to `config.yml` that were done to perform the functional test over CircleCI. Revised url being used by the functional test. Functional test has been confirmed as passing locally.

**Pull request merged**
