### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by surchs**
After the first demo, we have gone through our codebase and cleaned up several things that were created during the prototype work.

### CODE REVIEW

**Comment by surchs** [comment]
This is looking really good already. I think what is left here is some renaming

- [ ] find a new name for the app itself
- [ ] refactor the names of the templates
- [ ] find a new name for the query app

**Comment by jarmoza** [comment]
Class, function name, variables, and template block renaming also in a future commit.

**Comment by jarmoza** [comment]
Will watch for the app and template renames. Looks good otherwise.

**Comment by jarmoza** [comment]
Hey. Can you explain what's going on in https://github.com/metaneuro/concept_query/pull/79/commits/d0e034c3e1f656935e09a14b760205631ba025fa ?

There are some js code changes in the assets folder?

**Comment by surchs** [comment]
Ah, good spot. I think this must have happened during an inadvertent code cleanup from my IDE. It seems that the only change was that some semicolons were removed from .js files. If you prefer, we can revert these changes.

**Comment by jarmoza** [comment]
In order to run a query successfully, I had to `makemigrations` and then `migrate`. I think the sqlite database needs to be committed in that form.

**Comment by jarmoza** [comment]
Also - no need to revert the semicolons, but there was one logic change with an `if-else` statement that should be looked at.

**Comment by surchs** [comment]
Oh wow. Again, great catch. This is not good. I have no idea where these changes are coming from. I feel like I'd rather roll back these changes and understand why they were made and then rename this again.

**Comment by surchs** [comment]
OK, I think we are good to merge this.

**Pull request merged**
