### PR TITLE
Pipenv section for 'How to Contribute' in README

### PR DESCRIPTION
**Pull request by jarmoza**
… via pipenv

### CODE REVIEW

**Comment by surchs** [comment]
Thanks for the PR @jarmoza! I think your readme does resolve the Pipefile.lock problem we ran into. But it also sidesteps the deterministic dev environment that the pipenv lockfile is supposed to create. So I'm wondering if pipenv is actually a good solution for us. [According to their docs](https://pipenv.pypa.io/en/latest/), pipenv does:
1. convenience method to combine pip and venv so you no longer have to create your own virtualenvs (and run `pip install`)
2. resolve version conflicts in python dependencies of our project (all the way down)
3. "freeze" the versions of all dependencies in a more thorough way than what `pip freeze` does, to create a more deterministic environment, and making it easier to update the dependencies from one freeze to the next

I think 1. is nice but not needed, 2. is the responsibility of the maintainers of our dependencies and probably won't happen often  / at all. 

So 3. is really the main thing `pipenv` does for us. [The `pipenv` workflow](https://pipenv-fork.readthedocs.io/en/latest/advanced.html#using-pipenv-for-deployments) there is to run `pipenv lock` once, commit the lockfile to VCS, and then run `pipenv sync` on all other dev environments to ensure that the exact same versions are used (based on hashes). For deployment, ensuring a deterministic environment is most likely better done by containerizing the app - and we are going to do this any way. I don't know how important it will be to ensure exact python dependency versions across separate container versions, but once a container is built, we should not have any surprises.

So the only thing remaining are our local development environments that we work on until something is ready to deploy in a container. I am not sure that we really need such a fine grained control of dependency versions there - hopefully our app doesn't just implode if there is a slight version mismatch. But if it is important to pin versions, then I see the point of not doing that with the `requirements.txt` and using something with a lock ability instead. But: `pipenv` doesn't do that step reliably because of its inability to specify versions conditional on the OS of the dev environment. 

Having thought a bit about this now, I think there are two ways forward:
1. Drop pipenv and go back to `requirements.txt` to outline what is needed for the dev and test environments. They'll be used in the Docker container recipe to define the env in there
2. Switch to poetry. It has a bunch of nice things going for it 
  - uses the default pyproject.toml to keep the config - no need for an additional config file
  - is able to have [conditional dependency pins](https://python-poetry.org/docs/dependency-specification/#using-environment-markers) (including for OS version)
  - has a more [continuous release cycle](https://github.com/python-poetry/poetry/tags)

Sorry for the long rant here. But I think this is the right place to discuss what to do with the dependency management thing. Let me know what your thoughts are.

**Comment by jarmoza** [comment]
I think the issue here is then that we have two potential development cases. The first is a containerized development process, and the second is local development – which external collaborators may be interested in if containerization proves to be to much of a technical hurdle for them.

How about doing both – switching to `poetry` so that local development sans containerization is possible and using poetry in the app's container setup?

**Comment by jarmoza** [comment]
Something else to consider here for the containerization aspect is Docker's new dev environments: https://docs.docker.com/desktop/dev-environments/

**Comment by surchs** [comment]
Yes, I think that's a good idea. I realize that deploying apps may have more stringent version requirements, so having a tool ready to go that can deal with this is a good idea. Let's setup poetry then. I think it'll make sense to do that in this PR. 

The docker dev env looks interesting. I am not sure I fully get what it does (than freeze your current system state?). My main issue with what I have seen so far are that it is linked to docker desktop (not something I use), and also dockerhub (something that has recently changed their image retention policies and has a commercial goal). So I'd rather stay away from it. But it could be a good thing to look at anyway to understand how they make it easy to exchange deterministic dev environments quickly.

**Pull request closed without merging**
